### ISSUE TITLE
WECUI Forge

### ISSUE THREAD

**Issue by bloodmc** [Mumfrey/WorldEditCUI#22]
I want to attempt to get FTB to include WECUI in their modpacks but it will be a tough sell to also require them to include Liteloader. Would it be possible to make a Forge version that does not require liteloader? 

Whenever I mention WECUI, users ALWAYS refer to the "Forge edition" which is seen here

https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2

Reason I ask this is it would be nice to have any FTB server using GP to not have to worry about informing their users on how to install WECUI/liteloader.

Thoughts?

**Comment by bloodmc** [comment]
@Mumfrey any word on this? Would be nice to have a Forge version that doesn't require liteloader.

**Comment by Mumfrey** [comment]
I don't understand the reluctance to bundle LiteLoader with the modpack though, I've seen forge mods which bundle much larger and more invasive dependencies but because they're "forge native" there's no push back. Maybe I should rebrand it as _MumfreyCore_ and then everyone would be fine with it. I can understand the opposite being true - not wanting to install all of Forge to get a simple mod like WECUI - which is why this is a litemod in the first place. LiteLoader is extremely non-invasive and since the core of LiteLoader basically *became* Mixin, a bunch of Forge mods are effectively using LiteLoader unwittingly already, albeit without the mod-loading part and without LiteLoader's callbacks (which are just mixins which call ASM-generated (eg. extremely fast) handler lists).

I probably could write a Forge version but it would be pretty distinct from this version, since everything that isn't rendering is provided by LiteLoader's convenience classes for config, settings pages, IMC and plugin channels.

From this corner it basically looks like I'm being asked to rewrite something which works perfectly well under Forge already - a lot of work which will take away from the already meagre amount of time I have for working on more important things like Mixin - simply to appease some kind of philosophical objection to including an extra mod, just because of... well I don't understand root of the objection.

Basically to make this non-liteloader I have to take all the functionality I'm using of LiteLoader's and either find forge equivalents (some are available) and for those that aren't available I have to extract some of LiteLoader's functionality that I'm using in this mod and either make a standalone MumfreyCore library containing those parts or merge them into the mod and not use them when running on LiteLoader. I don't want to merge them here obviously because this mod is EPL and LiteLoader is All Rights Reserved so I either have to open-source those pieces or wrap and bundle them separately.

If we were in the situation where LiteLoader couldn't be simply and easily bundled in a modpack and effectively work just like any of the other dozens of FooCore mods I would understand, but that's not the case. It works trivially and quietly and also acts as a "core" for any one of dozens of other litemods that exist in the wild.

I realise this is a bit of an emotionally driven response but it's hard not to take it personally when I've worked for 6 years on a project which is not only finally accepted instead of being widely ridiculed, and whose core was ripped out to provide a key part of the Sponge reference implementation. I just don't understand the stigma that seems to be attached purely through the inclusion of the word "Loader" in the name.

Maybe if I renamed it to _MixinsPlusSomeOtherUsefulStuff_ and pretended it was a Forge mod there would be less friction.

**Comment by bloodmc** [comment]
Ok it makes perfect sense why you don’t have a forge version. I also agree completely on other mods requiring various dependencies yet no one complains about that. 

So the only other issue I’ve heard is liteloader increasing the startup time by a good amount using latest Forge. Would you be able to test this?

Thanks again for the update.

**Comment by Mumfrey** [comment]
> So the only other issue I’ve heard is liteloader increasing the startup time by a good amount using latest Forge. Would you be able to test this?

Dockter and Zidane mentioned something about stitching with LL installed, I've been so busy since Feb that I haven't had a chance to look into any of the backlog of issues with Mixin and LL both. I have Jun and July almost completely clear though so I'm going to be processing the outstanding issues over the next few weeks. I can definitely look into the issue in question.

**Comment by bloodmc** [comment]
OK thanks! I'll create a new ticket as this issue is unrelated.
