### ISSUE TITLE
Jittery Rendering at high Coordinate values

### ISSUE THREAD

**Issue by rcmaehl** [Mumfrey/WorldEditCUI#5]
Sorry about the lack of smoothness in the video, other laptop had just booted up and wouldn't display more than ~20fps due to resource usage.

http://youtu.be/fbl3iUvBy2k

**Comment by Mumfrey** [comment]
Okay I see what that is, that's not what I'd call *jitter* (which is when the object appears to be jumping back and forth when you look at it) but it's actually corruption of the grid itself because of the loss of precision in the values being used to draw the grid at very high values. That's reasonably simple to solve so I'll take a look at it.
